stanfy/helium

helium/src/main/groovy/com/stanfy/helium/dsl/scenario/ScenarioDelegate.groovy
helium/src/main/groovy/com/stanfy/helium/dsl/scenario/ScenarioInvoker.groovy
helium/src/test/groovy/com/stanfy/helium/dsl/scenario/ScenarioDelegateSpec.groovy

Detect bad sytax when method is invoked in a scenario

---

helium/src/main/groovy/com/stanfy/helium/dsl/ConfigurableServiceMethod.groovy
helium/src/main/groovy/com/stanfy/helium/dsl/FieldsBuilder.groovy
helium/src/main/groovy/com/stanfy/helium/dsl/MultipartBuilder.groovy
helium/src/main/groovy/com/stanfy/helium/dsl/TypeAwareBuilder.groovy
helium/src/main/groovy/com/stanfy/helium/handler/codegen/java/retrofit/RetrofitInterfaceGenerator.java
helium/src/main/groovy/com/stanfy/helium/model/DataType.groovy
helium/src/main/groovy/com/stanfy/helium/model/FileType.groovy
helium/src/main/groovy/com/stanfy/helium/model/FormType.groovy
helium/src/main/groovy/com/stanfy/helium/model/MultipartType.groovy
helium/src/main/groovy/com/stanfy/helium/model/ServiceMethod.groovy
helium/src/test/groovy/com/stanfy/helium/dsl/ProjectDslSpec.groovy
helium/src/test/groovy/com/stanfy/helium/handler/codegen/java/retrofit/RetrofitInterfaceGeneratorSpec.groovy

According to issue #92. This includes only parsing DSL to build corresponding model and generation of retrofit interfaces for new model.

Body request types model

---

helium/src/main/groovy/com/stanfy/helium/handler/codegen/java/entity/MessageToJavaClass.java

Make generated toString when fields have java keyword names.

Fix save toString generation

---

helium/src/main/groovy/com/stanfy/helium/handler/codegen/java/retrofit/RetrofitInterfaceGenerator.java
helium/src/test/groovy/com/stanfy/helium/handler/codegen/java/retrofit/RetrofitInterfaceGeneratorSpec.groovy
samples/java-retrofit/src/api/my-backend.api
samples/java-retrofit/src/main/java/com/stanfy/helium/sample/retrofit/Sample.java
samples/java-retrofit/src/test/java/com/stanfy/helium/sample/retrofit/SampleTest.java

Respect sequence attribute

---

codegen/README.md
command-line/src/main/groovy/com/stanfy/helium/cli/Main.groovy

Here you will find notes how to add a new module and start using it in the command line tool.
@PaulTaykalo @a-voronov 
Please review and let me know if you have any questions.

Add code generation start guide

---

codegen/java/java-entities/src/main/java/com/stanfy/helium/handler/codegen/java/entity/MessageToJavaClass.java
codegen/java/java-entities/src/test/java/com/stanfy/helium/handler/codegen/java/entity/PojoWriterSpec.groovy
codegen/java/java-handler/src/main/java/com/stanfy/helium/handler/codegen/java/JavaGeneratorOptions.java

Represent dictionary fields as maps

---

CHANGELOG.md
codegen/json/json-schema/src/main/groovy/com/stanfy/helium/handler/codegen/json/schema/JsonType.java
codegen/swagger/build.gradle
codegen/swagger/src/main/java/com/stanfy/helium/swagger/Definition.java
codegen/swagger/src/main/java/com/stanfy/helium/swagger/Parameter.java
codegen/swagger/src/main/java/com/stanfy/helium/swagger/Path.java
codegen/swagger/src/main/java/com/stanfy/helium/swagger/Root.java
codegen/swagger/src/main/java/com/stanfy/helium/swagger/SwaggerHandler.java
codegen/swagger/src/test/groovy/com/stanfy/helium/swagger/SwaggerHandlerSpec.groovy
settings.gradle

Start swagger integration

---

helium/src/main/groovy/com/stanfy/helium/internal/entities/BaseConverter.java
helium/src/test/groovy/com/stanfy/helium/format/json/JsonReadFormatSpec.groovy

Fix arrays validation issue

---

codegen/json/json-schema/src/main/groovy/com/stanfy/helium/handler/codegen/json/schema/JsonSchemaEntity.java
codegen/json/json-schema/src/main/groovy/com/stanfy/helium/handler/codegen/json/schema/JsonSchemaGenerator.groovy
codegen/json/json-schema/src/main/groovy/com/stanfy/helium/handler/codegen/json/schema/SchemaBuilder.groovy
codegen/json/json-schema/src/test/groovy/com/stanfy/helium/handler/codegen/json/schema/JsonSchemaGeneratorSpec.groovy
codegen/json/json-schema/src/test/groovy/com/stanfy/helium/handler/codegen/json/schema/SchemaBuilderSpec.groovy
codegen/swagger/src/main/java/com/stanfy/helium/swagger/Definition.java
codegen/swagger/src/main/java/com/stanfy/helium/swagger/Path.java
codegen/swagger/src/main/java/com/stanfy/helium/swagger/Root.java
codegen/swagger/src/main/java/com/stanfy/helium/swagger/SwaggerHandler.java
codegen/swagger/src/test/groovy/com/stanfy/helium/swagger/SwaggerHandlerSpec.groovy
gradle-plugin/build.gradle
gradle-plugin/src/main/groovy/com/stanfy/helium/gradle/HeliumInitializer.groovy
gradle-plugin/src/main/groovy/com/stanfy/helium/gradle/tasks/SwaggerTask.groovy
gradle-plugin/src/test/groovy/com/stanfy/helium/gradle/HeliumPluginSpec.groovy
samples/swagger/build.gradle
samples/swagger/uber.api

Add first swagger integration test

---

helium/src/main/groovy/com/stanfy/helium/internal/dsl/ConfigurableService.groovy
helium/src/main/groovy/com/stanfy/helium/model/Security.groovy
helium/src/main/groovy/com/stanfy/helium/model/Service.groovy
helium/src/test/groovy/com/stanfy/helium/internal/dsl/ProjectDslSpec.groovy

Add security definition to DSL

---

codegen/swagger/src/main/java/com/stanfy/helium/swagger/Path.java
codegen/swagger/src/main/java/com/stanfy/helium/swagger/SwaggerHandler.java
codegen/swagger/src/test/groovy/com/stanfy/helium/swagger/SwaggerHandlerSpec.groovy

Add operation id generation

---

codegen/json/json-schema/src/main/groovy/com/stanfy/helium/handler/codegen/json/schema/JsonType.java
codegen/json/json-schema/src/main/groovy/com/stanfy/helium/handler/codegen/json/schema/SchemaBuilder.groovy
codegen/swagger/src/main/java/com/stanfy/helium/swagger/Path.java
codegen/swagger/src/main/java/com/stanfy/helium/swagger/SwaggerHandler.java
codegen/swagger/src/test/groovy/com/stanfy/helium/swagger/SwaggerHandlerSpec.groovy

/cc @Vandalko 
Another piece of #111.

Add quick support for multipart

---

helium/src/main/groovy/com/stanfy/helium/internal/dsl/FieldsBuilder.groovy
helium/src/test/groovy/com/stanfy/helium/internal/dsl/ProjectDslSpec.groovy

Make sequences required by default

---

codegen/swift/swift-entities/src/main/kotlin/com/stanfy/helium/handler/codegen/swift/entity/SwiftDefaultHandler.kt
codegen/swift/swift-entities/src/main/kotlin/com/stanfy/helium/handler/codegen/swift/entity/entities/SwiftEntitiesGenerator.kt
codegen/swift/swift-entities/src/test/groovy/com/stanfy/helium/handler/codegen/swift/entity/SwiftDefaultHandlerTest.groovy
codegen/swift/swift-entities/src/test/groovy/com/stanfy/helium/handler/codegen/swift/entity/entities/SwiftEntitiesGeneratorImplTest.groovy
codegen/swift/swift-entities/src/test/groovy/com/stanfy/helium/handler/codegen/swift/entity/entities/SwiftEntitiesPropertiesGeneratorImplTest.groovy

[WIP]Swift Custom mappings support

---

build.gradle
command-line/README.md
command-line/build.gradle
command-line/src/cmd-test/run
command-line/src/launcher/helium.sh

It will be available on Maven Central repo. We'll be able to download it using HTTPs in our future helium shell script.
/cc @PaulTaykalo

Publish nodeps jar

---

helium/src/main/groovy/com/stanfy/helium/format/json/JsonFormatProvider.java
helium/src/main/groovy/com/stanfy/helium/handler/tests/HttpExecutor.java
helium/src/main/groovy/com/stanfy/helium/handler/tests/RequestBodyBuilder.java
helium/src/main/groovy/com/stanfy/helium/handler/tests/body/BytesBodyBuilder.groovy
helium/src/main/groovy/com/stanfy/helium/handler/tests/body/FormBodyBuilder.groovy
helium/src/main/groovy/com/stanfy/helium/handler/tests/body/JsonConverterBuilder.groovy
helium/src/main/groovy/com/stanfy/helium/handler/tests/body/MultipartBodyBuilder.groovy
helium/src/main/groovy/com/stanfy/helium/internal/dsl/DefaultTypeResolver.groovy
helium/src/main/groovy/com/stanfy/helium/internal/entities/MessageConverter.java
helium/src/main/groovy/com/stanfy/helium/internal/entities/TypedEntityValueBuilder.groovy
helium/src/main/groovy/com/stanfy/helium/model/Message.groovy
helium/src/test/groovy/com/stanfy/helium/format/json/JsonReadFormatSpec.groovy
helium/src/test/groovy/com/stanfy/helium/format/json/JsonWriteFormatSpec.groovy
helium/src/test/groovy/com/stanfy/helium/internal/entities/TypedEntityValueBuilderSpec.groovy

/cc @Vandalko @PaulTaykalo @Burbaka 
This should unblock writing tests in our specs.

Support vnd+json and parent fields in tests

---

helium/src/test/groovy/com/stanfy/helium/format/json/JsonFormatProviderSpec.groovy

Add supported media types test

---

build.gradle
codegen/java/java-entities/src/main/java/com/stanfy/helium/handler/codegen/java/entity/AndroidParcelableWriter.java
codegen/java/java-entities/src/main/java/com/stanfy/helium/handler/codegen/java/entity/MessageToJavaClass.java
codegen/java/java-entities/src/test/groovy/com/stanfy/helium/handler/codegen/java/entity/AndroidParcelableWriterSpec.groovy
codegen/java/java-entities/src/test/groovy/com/stanfy/helium/handler/codegen/java/entity/BaseMessageToClassGeneratorSpec.groovy
codegen/java/java-entities/src/test/groovy/com/stanfy/helium/handler/codegen/java/entity/EntitiesGeneratorSpec.groovy
codegen/java/java-entities/src/test/groovy/com/stanfy/helium/handler/codegen/java/entity/PojoWriterSpec.groovy
codegen/java/java-handler/src/main/java/com/stanfy/helium/handler/codegen/java/JavaGeneratorOptions.java
command-line/src/cmd-test/run
command-line/src/launcher/helium.sh
gradle-plugin/src/main/groovy/com/stanfy/helium/gradle/HeliumExtension.groovy
samples/android/build.gradle
samples/custom-data-types/build.gradle
samples/httpbin/build.gradle
samples/java-retrofit/build.gradle
samples/json-scheme/build.gradle
samples/multi-imports/build.gradle
samples/multiple-specs/build.gradle
samples/objc-gradle/build.gradle
samples/swagger/build.gradle
samples/tests-with-gradle/build.gradle
samples/unresolved-headers/build.gradle

/cc @Vandalko @nazlo 
Now if you define a custom type mapping for a generator, it does not need to be in the classpath.
Also closes #76

Remove classpath requirement for custom mappings

---

codegen/java/java-entities/src/test/groovy/com/stanfy/helium/handler/codegen/java/entity/PojoWriterSpec.groovy
helium/src/main/groovy/com/stanfy/helium/model/Field.groovy
helium/src/test/groovy/com/stanfy/helium/internal/dsl/ProjectDslSpec.groovy
helium/src/test/groovy/com/stanfy/helium/internal/utils/NamesSpec.groovy
helium/src/test/groovy/com/stanfy/helium/model/FieldSpec.groovy

Allow to define fields with @ character in DSL documents
@roman-mazur @Vandalko please review

Allow to define fields with @ character in DSL documents

---

codegen/java/java-entities/src/main/java/com/stanfy/helium/handler/codegen/java/entity/AndroidParcelableWriter.java
codegen/java/java-entities/src/test/groovy/com/stanfy/helium/handler/codegen/java/entity/AndroidParcelableWriterSpec.groovy
samples/android/build.gradle
samples/android/src/api/twitter.api
samples/android/src/main/java/com/stanfy/helium/sample/android/CustomType.java

Fix custom sequences serialization

---

helium/src/main/groovy/com/stanfy/helium/internal/dsl/TypeDsl.groovy

Quick fix of https://github.com/stanfy/helium/issues/171

Wrap custom readers

---

helium/src/test/groovy/com/stanfy/helium/handler/tests/HttpExecutorAuthSpec.groovy
helium/src/test/groovy/com/stanfy/helium/handler/tests/HttpExecutorSpec.groovy

This test ensures we properly perform client credentials token retrieval when tests
are run with oauth authorization flow.

Add integration test for oauth intercetopr

---

codegen/java/java-entities/src/main/java/com/stanfy/helium/handler/codegen/java/entity/GsonPojoWriter.java
codegen/java/java-entities/src/test/groovy/com/stanfy/helium/handler/codegen/java/entity/GsonPojoWriterSpec.groovy
helium/build.gradle
helium/src/main/groovy/com/stanfy/helium/HeliumWriter.groovy
helium/src/main/groovy/com/stanfy/helium/model/Field.groovy
helium/src/test/groovy/com/stanfy/helium/HeliumWriterSpec.groovy
helium/src/test/groovy/com/stanfy/helium/model/FieldSpec.groovy

GSON supports alternate names since [version 2.4](https://github.com/google/gson/blob/master/CHANGELOG.md#version-24)

Support GSON alternatives

---

codegen/swift/swift-entities/src/main/kotlin/com/stanfy/helium/handler/codegen/swift/entity/client/SwiftAPIClientGenerator.kt
codegen/swift/swift-entities/src/main/kotlin/com/stanfy/helium/handler/codegen/swift/entity/registry/SwiftTypeRegistyy.kt
codegen/swift/swift-entities/src/main/resources/client/SwiftAPIClientCore.mustache
command-line/build.gradle
command-line/src/cmd-test/swift-gen-run.sh
command-line/src/cmd-test/test.api
gradle/integration-tests.gradle

@PaulTaykalo would you suggest me how to add a test? I do not even know if it compiles... :)

Use EmptyResponse in swift code for no responses

---

codegen/swift/swift-entities/src/main/kotlin/com/stanfy/helium/handler/codegen/swift/entity/client/SwiftAPIClientGenerator.kt
codegen/swift/swift-entities/src/test/groovy/com/stanfy/helium/handler/codegen/swift/entity/client/SwiftApiClientGeneratorTest.groovy

fyi @evgenbakumenko @PaulTaykalo @PaulLafitskyi

Fix Swift path patterns generation
